apiVersion: v2
name: gitea
description: Gitea Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: 1.20.5
icon: https://gitea.com/assets/img/logo.svg

keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
sources:
  - https://gitea.com/gitea/helm-chart
  - https://github.com/go-gitea/gitea
  - https://hub.docker.com/r/gitea/gitea/
