apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: goedel-sandbox
spec:
  tasks:
    - name: clone-repo
      params:
        - name: url
          value: 'https://github.com/gratinierer/oc_pipeline.git'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
        - name: userHome
          value: /home/git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: goedel-ws
    - name: install-gitea
      params:
        - name: charts_dir
          value: helm/gitea_full_template
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: gitea
        - name: release_namespace
          value: ''
        - name: overwrite_values
          value: ''
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: ''
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: goedel-ws
    - name: install-jenkins
      params:
        - name: charts_dir
          value: helm/jenkins
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: jenkins
        - name: release_namespace
          value: ''
        - name: overwrite_values
          value: ''
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: ''
      runAfter:
        - install-gitea
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: goedel-ws
    - name: install-mariadb
      params:
        - name: charts_dir
          value: helm/mariadb-ephemeral
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: mariadb
        - name: release_namespace
          value: ''
        - name: overwrite_values
          value: ''
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: ''
      runAfter:
        - install-jenkins
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: goedel-ws
    - name: install-db-connector
      params:
        - name: charts_dir
          value: helm/goedel-db-connector
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: ws
        - name: release_namespace
          value: ''
        - name: overwrite_values
          value: ''
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: ''
      runAfter:
        - install-mariadb
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: goedel-ws
    - name: install-superset
      params:
        - name: charts_dir
          value: helm/superset
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: superset
        - name: release_namespace
          value: ''
        - name: overwrite_values
          value: ''
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: ''
      runAfter:
        - install-db-connector
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: goedel-ws
  workspaces:
    - name: goedel-ws
