kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  name: {{ include "goedel-db-connector.fullname" . }}
  labels:
    {{- include "goedel-db-connector.labels" . | nindent 4 }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "goedel-db-connector.name" . }}:latest
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.9-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/gratinierer/python_serverless.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: python-serverless-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: python-serverless-git-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
