kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "goedel-db-connector.fullname" . }}
  labels:
    {{- include "goedel-db-connector.labels" . | nindent 4 }}
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: dbconnector-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: dbconnector-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/gratinierer/oc_pipeline.git'
    contextDir: /app/db-connector
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "goedel-db-connector.name" . }}:latest
  resources: {}
  postCommit: {}
