apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "goedel-db-connector.name" . }}
  labels:
    {{- include "goedel-db-connector.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true

