apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/gratinierer/python_serverless.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"python-serverless-git:latest","namespace":"gratinierer-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"python-serverless-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
    serving.knative.dev/creator: gratinierer
    serving.knative.dev/lastModifier: gratinierer
  resourceVersion: '1337876863'
  name: {{ include "goedel-db-connector.fullname" . }}
  namespace: gratinierer-dev
  labels:
    {{- include "goedel-db-connector.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '100'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
      creationTimestamp: null
    labels:
      {{- include "goedel-db-connector.labels" . | nindent 8 }}
    spec:
      containerConcurrency: 0
      containers:
        - image: {{ include "goedel-db-connector.fullname" . }}:latest
          imagePullPolicy: Always
          name: {{ include "goedel-db-connector.fullname" . }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100