apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "{{ include "goedel-db-connector.name" . }}:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  name: {{ include "goedel-db-connector.fullname" . }}
  namespace: gratinierer-dev
  labels:
    {{- include "goedel-db-connector.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '100'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
      creationTimestamp: null
    labels:
      {{- include "goedel-db-connector.labels" . | nindent 8 }}
    spec:
      containerConcurrency: 0
      containers:
        - image: {{ include "goedel-db-connector.name" . }}:latest
          imagePullPolicy: Always
          name: {{ include "goedel-db-connector.name" . }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100