apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    name: mariadb

